--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.105.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 11. 14. 18:16:15
-- Server version: 10.4.28
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO iktato.beosztasok(Id_Beosztas, Beosztas) VALUES
(6, 'Árubeszerző         '),
(7, 'Belső ellenőr       '),
(5, 'Értékesítő          '),
(2, 'Főmérnök            '),
(1, 'Igazgató            '),
(8, 'Rakodó              '),
(10, 'Raktáros            '),
(9, 'Szalagvezető        ');


INSERT INTO iktato.iktat(Id_Iktat, Iktatoszam, IdUser, Datum, IdTema, Leiras) VALUES
(2, '458                 ', 3, '2023-10-25', 2, 'uvtft                                             '),
(3, '2023/014            ', 3, '2023-10-10', 2, 'iofrdzkj                                          '),
(4, '2023/015            ', 5, '2023-10-11', 1, 'iőhourcz u9z8 v7                                  '),
(5, '2023/016            ', 6, '2023-10-11', 1, 'nukguf uhuzz                                      '),
(6, '2023/017            ', 5, '2023-10-11', 1, 'hkhui                                             '),
(7, '20231010/1          ', 6, '2023-10-10', 4, 'iubvzd ftdfr                                      ');


INSERT INTO iktato.osztalyok(Id_Osztaly, Osztaly) VALUES
(4, 'Beruházás           '),
(3, 'Beszerzés           '),
(2, 'Értékesítés         '),
(1, 'Igazgatóság         '),
(5, 'Kontrolling         '),
(6, 'Termelés            ');


INSERT INTO iktato.temak(Id_Tema, Tema) VALUES
(1, 'Beszerzés           '),
(2, 'Értékesítés         '),
(4, 'Raktározás          '),
(3, 'Ügyfél reklamációk  ');


INSERT INTO iktato.users(Id_User, Nev, Jelszo, Admin) VALUES
(1, 'Attila              ', '1234      ', 1),
(3, 'Zsuzsa              ', '1234      ', 0),
(5, 'Alma                ', '1234      ', 0),
(6, 'Feri                ', '1234      ', 0),
(7, 'Ármin               ', '1234      ', 0),
(8, 'Zsolti              ', '1234      ', 0),
(9, 'Berci               ', '1234      ', 0),
(10, 'Zoli                ', '1234      ', 0),
(1008, 'Margó               ', '1234      ', 1);